package com.sedlacek.quiz.models;

import java.util.Map;

public class States {
    public static final Map<String, String> Europe = Map.ofEntries(
            Map.entry("Albánie", "Tirana"),
            Map.entry("Andorra", "Andorra la Vella"),
            Map.entry("Arménie", "Jerevan"),
            Map.entry("Ázerbájdžán", "Baku"),
            Map.entry("Belgie", "Brusel"),
            Map.entry("Bělorusko", "Minsk"),
            Map.entry("Bosna a Hercegovina", "Sarajevo"),
            Map.entry("Bulharsko", "Sofie"),
            Map.entry("Černá Hora", "Podgorica"),
            Map.entry("Česká republika", "Praha"),
            Map.entry("Dánsko", "Kodaň"),
            Map.entry("Estonsko", "Tallinn"),
            Map.entry("Finsko", "Helsinki"),
            Map.entry("Francie", "Paříž"),
            Map.entry("Gruzie", "Tbilisi"),
            Map.entry("Chorvatsko", "Záhřeb"),
            Map.entry("Irsko", "Dublin"),
            Map.entry("Island", "Reykjavík"),
            Map.entry("Itálie", "Řím"),
            Map.entry("Kazachstán", "Astana"),
            Map.entry("Kosovo", "Priština"),
            Map.entry("Kypr", "Nikósie"),
            Map.entry("Lichtenštejnsko", "Vaduz"),
            Map.entry("Litva", "Vilnius"),
            Map.entry("Lotyšsko", "Riga"),
            Map.entry("Lucembursko", "Lucemburk"),
            Map.entry("Maďarsko", "Budapešť"),
            Map.entry("Malta", "Valletta"),
            Map.entry("Moldavsko", "Kišiněv"),
            Map.entry("Monako", "Monaco-Ville"),
            Map.entry("Německo", "Berlín"),
            Map.entry("Nizozemsko", "Amsterdam"),
            Map.entry("Norsko", "Oslo"),
            Map.entry("Polsko", "Varšava"),
            Map.entry("Portugalsko", "Lisabon"),
            Map.entry("Rakousko", "Vídeň"),
            Map.entry("Rumunsko", "Bukurešť"),
            Map.entry("Rusko", "Moskva"),
            Map.entry("Řecko", "Atény"),
            Map.entry("San Marino", "San Marino"),
            Map.entry("Severní Makedonie", "Skopje"),
            Map.entry("Slovensko", "Bratislava"),
            Map.entry("Slovinsko", "Lublaň"),
            Map.entry("Spojené království", "Londýn"),
            Map.entry("Srbsko", "Bělehrad"),
            Map.entry("Španělsko", "Madrid"),
            Map.entry("Švédsko", "Stockholm"),
            Map.entry("Švýcarsko", "Bern"),
            Map.entry("Turecko", "Ankara"),
            Map.entry("Ukrajina", "Kyjev"),
            Map.entry("Vatikán", "Vatikán")
    );

    public static final Map<String, String> AsiaAndOceania = Map.ofEntries(
            Map.entry("Afghánistán", "Kábul"),
            Map.entry("Arménie", "Jerevan"),
            Map.entry("Austrálie", "Canberra"),
            Map.entry("Ázerbájdžán", "Baku"),
            Map.entry("Bahrajn", "Manáma"),
            Map.entry("Bangladéš", "Dháka"),
            Map.entry("Bhútán", "Thimbú"),
            Map.entry("Brunej", "Bandar Seri Begawan"),
            Map.entry("Čína", "Peking"),
            Map.entry("Egypt", "Káhira"),
            Map.entry("Filipíny", "Manila"),
            Map.entry("Gruzie", "Tbilisi"),
            Map.entry("Indie", "Nové Dillí"),
            Map.entry("Indonésie", "Jakarta"),
            Map.entry("Irák", "Bagdád"),
            Map.entry("Írán", "Teherán"),
            Map.entry("Izrael", "Jeruzalém"),
            Map.entry("Japonsko", "Tokio"),
            Map.entry("Jemen", "San'á"),
            Map.entry("Jižní Korea", "Soul"),
            Map.entry("Jordánsko", "Ammán"),
            Map.entry("Kambodža", "Phnompenh"),
            Map.entry("Katar", "Dauhá"),
            Map.entry("Kazachstán", "Astana"),
            Map.entry("Kuvajt", "Kuvajt"),
            Map.entry("Kypr", "Nikósie"),
            Map.entry("Kyrgyzstán", "Biškek"),
            Map.entry("Laos", "Vientiane"),
            Map.entry("Libanon", "Bejrút"),
            Map.entry("Malajsie", "Kuala Lumpur"),
            Map.entry("Maledivy", "Male"),
            Map.entry("Mongolsko", "Ulánbátar"),
            Map.entry("Myanmar", "Neipyijto"),
            Map.entry("Omán", "Maskat"),
            Map.entry("Nepál", "Káthmándú"),
            Map.entry("Nový Zéland", "Wellington"),
            Map.entry("Pákistán", "Islámábád"),
            Map.entry("Rusko", "Moskva"),
            Map.entry("Saúdská Arábie", "Rijád"),
            Map.entry("Severní Korea", "Pchjongjang"),
            Map.entry("Singapur", "Singapur"),
            Map.entry("Spojené arabské emiráty", "Abú Dhabí"),
            Map.entry("Srí Lanka", "Šrí Džajavardanapura Kotte"),
            Map.entry("Sýrie", "Damašek"),
            Map.entry("Tádžikistán", "Dušanbe"),
            Map.entry("Thajsko", "Bangkok"),
            Map.entry("Tchaj-wan", "Tchaj-pej"),
            Map.entry("Turecko", "Ankara"),
            Map.entry("Turkmenistán", "Ašchabad"),
            Map.entry("Uzbekistán", "Taškent"),
            Map.entry("Vietnam", "Hanoj"),
            Map.entry("Východní Timor", "Dili")
    );

    public static final Map<String, String> NorthAndSouthAmerica = Map.ofEntries(
            Map.entry("Kanada", "Ottawa"),
            Map.entry("Spojené státy americké", "Washington, D.C."),
            Map.entry("Mexiko", "Mexico City"),
            Map.entry("Belize", "Belmopan"),
            Map.entry("Guatemala", "Guatemala"),
            Map.entry("Honduras", "Tegucigalpa"),
            Map.entry("Kostarika", "San José"),
            Map.entry("Nikaragua", "Managua"),
            Map.entry("Panama", "Panamá"),
            Map.entry("Salvador", "San Salvador"),
            Map.entry("Dominikánská republika", "Santo Domingo"),
            Map.entry("Jamajka", "Kingston"),
            Map.entry("Kuba", "Havana"),
            Map.entry("Argentina", "Buenos Aires"),
            Map.entry("Bolívie", "Sucre"),
            Map.entry("Brazílie", "Brasília"),
            Map.entry("Ekvádor", "Quito"),
            Map.entry("Guyana", "Georgetown"),
            Map.entry("Chile", "Santiago de Chile"),
            Map.entry("Kolumbie", "Bogotá"),
            Map.entry("Paraguay", "Asunción"),
            Map.entry("Peru", "Lima"),
            Map.entry("Surinam", "Paramaribo"),
            Map.entry("Venezuela", "Caracas")
    );

    public static final Map<String, String> Africa = Map.ofEntries(
            Map.entry("Alžírsko", "Alžír"),
            Map.entry("Angola", "Luanda"),
            Map.entry("Benin", "Porto Novo"),
            Map.entry("Botswana", "Gaborone"),
            Map.entry("Burundi", "Gitega"),
            Map.entry("Čad", "N'Djamena"),
            Map.entry("Džibutsko", "Džibuti"),
            Map.entry("Egypt", "Káhira"),
            Map.entry("Eritrea", "Asmara"),
            Map.entry("Etiopie", "Addis Abeba"),
            Map.entry("Gabon", "Libreville"),
            Map.entry("Gambie", "Banjul"),
            Map.entry("Ghana", "Akkra"),
            Map.entry("Guinea", "Konakry"),
            Map.entry("Guinea-Bissau", "Bissau"),
            Map.entry("Jihoafrická republika", "Pretoria"),
            Map.entry("Jižní Súdán", "Džuba"),
            Map.entry("Kamerun", "Yaoundé"),
            Map.entry("Kapverdy", "Praia"),
            Map.entry("Keňa", "Nairobi"),
            Map.entry("Komory", "Moroni"),
            Map.entry("Konžská republika", "Brazzaville"),
            Map.entry("Konžská demokratická republika", "Kinshasa"),
            Map.entry("Lesotho", "Maseru"),
            Map.entry("Libérie", "Monrovia"),
            Map.entry("Libye", "Tripolis"),
            Map.entry("Madagaskar", "Antananarivo"),
            Map.entry("Malawi", "Lilongwe"),
            Map.entry("Mali", "Bamako"),
            Map.entry("Maroko", "Rabat"),
            Map.entry("Mauricius", "Port Louis"),
            Map.entry("Mauritánie", "Nuakšott"),
            Map.entry("Mosambik", "Maputo"),
            Map.entry("Namibie", "Windhoek"),
            Map.entry("Niger", "Niamey"),
            Map.entry("Nigérie", "Abuja"),
            Map.entry("Pobřeží Slonoviny", "Yamoussoukro"),
            Map.entry("Rovníková Guinea", "Malabo"),
            Map.entry("Rwanda", "Kigali"),
            Map.entry("Senegal", "Dakar"),
            Map.entry("Seychely", "Victoria"),
            Map.entry("Sierra Leone", "Freetown"),
            Map.entry("Somálsko", "Mogadišo"),
            Map.entry("Středoafrická republika", "Bangui"),
            Map.entry("Súdán", "Chartúm"),
            Map.entry("Svatý Tomáš a Princův ostrov", "São Tomé"),
            Map.entry("Svazijsko", "Mbabane"),
            Map.entry("Tanzanie", "Dodoma"),
            Map.entry("Togo", "Lomé"),
            Map.entry("Tunisko", "Tunis"),
            Map.entry("Uganda", "Kampala"),
            Map.entry("Zambie", "Lusaka"),
            Map.entry("Zimbabwe", "Harare")
    );
}
